import { Brain, PieChart, Coins } from 'lucide-react'

const innovations = [
  {
    title: 'AI as Oracle',
    description: 'Let our AI agent be your trusted oracle, ensuring accurate market resolutions and helping you create new markets effortlessly.',
    icon: Brain,
  },
  {
    title: 'Revenue Sharing',
    description: 'Get a share of the fees generated by the market you create. The more active your market, the higher your earnings!',
    icon: PieChart,
  },
  {
    title: 'LP Rewards',
    description: 'Earn passive income by staking tokens on prediction markets. Your assets generate yield while supporting market liquidity.',
    icon: Coins,
  },
]

export default function CoreInnovations() {
  return (
    <section className="py-20 bg-gray-900">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold text-center mb-12 gradient-text">Core Innovations</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {innovations.map((innovation, index) => (
            <div key={index} className="bg-gray-800 rounded-lg p-6 shadow-xl hover:scale-105 transition-all duration-200 ease-in-out">
              <innovation.icon className="w-12 h-12 mb-4 text-purple-400" />
              <h3 className="text-xl font-semibold mb-2 text-white">{innovation.title}</h3>
              <p className="text-gray-300">{innovation.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

