import { Brain, Coins, PieChart, Bot } from 'lucide-react'

const features = [
  {
    title: 'AI-Powered Market Creation',
    description: 'Easily create prediction markets with the help of our intelligent AI assistant. Define events, outcomes, and timelines effortlessly.',
    icon: Brain,
  },
  {
    title: 'LP Rewards',
    description: 'Earn rewards by providing liquidity. Your staked tokens generate yield and LP rewards.',
    icon: Coins,
  },
  {
    title: 'Revenue Sharing',
    description: 'Market creators earn a share of the revenue generated by their markets, incentivizing creativity and participation.',
    icon: PieChart,
  },
  {
    title: 'AI Agent as Oracle',
    description: 'Our AI-driven oracle validates event results, ensuring accurate and consistent market resolutions.',
    icon: Bot,
  },
]

export default function Features() {
  return (
    <section id="features" className="py-20 bg-gray-800">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold text-center mb-12 gradient-text">Platform Features</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-gray-700 rounded-lg p-6 shadow-xl hover:scale-105 transition-all duration-200 ease-in-out">
              <feature.icon className="w-12 h-12 mb-4 text-purple-400" />
              <h3 className="text-xl font-semibold mb-2 text-white">{feature.title}</h3>
              <p className="text-gray-300">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

